[Setting]
test = 2
experiment = 6
filter = false
outlier_over_std = 3
min_data_filter = 10
minimum_plot_size = 3
output_file = 'output/record.csv'

[Plotting]
'font.size' = 17
'lines.linewidth' = 3.5
'legend.fontsize' = 22
'axes.labelsize' = 18
'axes.titlesize' = 22
'figure.figsize' = "10, 5"
'figure.autolayout' = true
'font.family' = 'PMingLiU'

[Wording]
title = "Stroop Effect 互動實驗"
description = "重現 J. Ridley Stroop 於 Studies of Interference in Serial Verbal Reactions 所發表的實驗"
index = "主頁面"
help = "規則說明"
test = "測試局"
results = "實驗結果"
experiment = "正式局"
back_button = "回到主畫面"
test_button = "試玩"
before_exp = "點選任意按鍵開始實驗，並同時開始計時"
between_exp = "點選任意按鍵繼續實驗"
exp_button = "正式開始"
end_of_experiment = "實驗結束，謝謝您的參與，以下是這次的數據："
help_message = """
進入實驗頁面時，您會看到一個九宮格，
按下鍵盤上紅綠藍任意按鍵會開始實驗，
九宮格會顯示文字/圖標，並開始計時。

您的任務就是依照九宮格內出現的文字/圖標的顏色，
（注意並不是文字寫的顏色，而是文字被塗上的顏色）
按下鍵盤上對應的按鍵。

九宮格中以粗框黑色標誌的為現在您要選擇顏色的文字/圖標，
順序由左至右，並由上至下，
當九宮格所有文字/圖標都結束之後，表格會刷新，
這時一樣按下鍵盤上紅綠藍任意按鍵繼續實驗。

試玩局共有 2 輪，正式實驗則有 6 輪，
請特別注意同時按下兩個以上的按鍵是被禁止的。

說明到此結束，謝謝您的閱讀，敬祝實驗順利。
"""
plot_x = '反應時間 (秒 / 100次反應)'
plot_y = '次數'
line_normal = '一般文字'
line_conflict = '衝突文字'
arrow_normal = '您的一般文字平均'
arrow_conflict = '您的衝突文字平均'
literature_image = "文獻實驗結果："
literature_image_discription="您的結果與 Stroop 的實驗結果相比較"
local_image = "實驗結果累計："
local_image_discription="於本模擬實驗網站進行的所有實驗結果"
