[Setting]
test = 2
experiment = 6
filter = false
outlier_over_std = 3
min_data_filter = 10
minimum_plot_size = 3
output_file = 'output/record.csv'

[Plotting]
'font.size' = 17
'lines.linewidth' = 3.5
'legend.fontsize' = 22
'axes.labelsize' = 18
'axes.titlesize' = 22
'figure.figsize' = "10, 5"
'figure.autolayout' = true
'font.family' = 'PMingLiU'

[Wording]
title = "Stroop Effect 互動實驗"
description = "重現 J. Ridley Stroop 於 Studies of Interference in Serial Verbal Reactions 所發表的實驗"
index = "主頁面"
help = "規則說明"
test = "測試局"
results = "實驗結果"
experiment = "正式局"
back_button = "回到主畫面"
test_button = "試玩"
before_exp = "點選任意按鍵開始實驗，並同時開始計時"
between_exp = "點選任意按鍵繼續實驗"
exp_button = "正式開始"
end_of_experiment = "實驗結束，謝謝您的參與，以下是這次的數據："
help_message = """
這裡是說明文字
第一行
第二行
第三行
"""
plot_x = '反應時間 (秒 / 100次反應)'
plot_y = '次數'
line_normal = '一般文字'
line_conflict = '衝突文字'
arrow_normal = '您的一般文字平均'
arrow_conflict = '您的衝突文字平均'
your_image = "您的實驗結果："
literature_image = "原始實驗結果："
